name: main-workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint -set_exit_status ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

  test:
    runs-on: ubuntu-20.04
    needs: build-and-lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Run tests
        run: go test -vet=off ./...

  audit:
    runs-on: ubuntu-20.04
    needs: build-and-lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

  build-deploy-list:
    runs-on: ubuntu-20.04
    needs: [test, audit]
    outputs:
      api_service: ${{ steps.filter.outputs.api_service }}
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            shared: &shared
              - .github/workflows/**
            api_service:
              - *shared
              - build/package/api-service.dockerfile
              - cmd/api-service/**

  deploy-api-gateway:
    runs-on: ubuntu-20.04
    needs: build-deploy-list
    if: ${{ github.event_name == 'push' && needs.build-deploy-list.outputs.api_service == 'true' }}
    steps:
      - name: deploy
        run: echo deploying api gateway

  deploy-api-service:
    runs-on: ubuntu-20.04
    needs: build-deploy-list
    if: ${{ github.event_name == 'push' && needs.build-deploy-list.outputs.api_service == 'true' }}
    steps:
      - name: deploy
        run: echo deploying api service
